on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/audit-workflow@int
        with:
          allowedEndpoints: |
            github.com.:443
            registry.npmjs.org.:443
            int.api.stepsecurity.io:443
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
